workflows:
  ios_unsigned_build:
    name: iOS Unsigned Build
    environment:
      vars:
        FLUTTER_VERSION: stable
        XCODE_WORKSPACE: "swiftly.xcworkspace" # <-- Put the name of your workspace here.
        XCODE_SCHEME: "swiftly" # <-- Put the name of your scheme here.
        BUNDLE_ID: "io.codemagic.swiftly" # <-- Put your Bundle Id here.
        APP_STORE_APPLE_ID: 1555555551
      flutter:
        version: "$FLUTTER_VERSION"
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default # Укажите конкретную версию Xcode
    triggering:
      events:
        - push
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS unsigned build
        script: |
          flutter build ios --no-codesign
    artifacts:
      - build/ios/Debug-iphoneos/*.app
