workflows:
  ios_simulator_build:
    name: iOS Simulator Build
    environment:
      vars:
        FLUTTER_VERSION: stable
      flutter:
        version: "$FLUTTER_VERSION"
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS simulator build
        script: |
          flutter build ios --simulator --no-codesign
      - name: Create app.zip
        script: |
          cd build/ios/iphonesimulator && zip -r app.zip *.app
    artifacts:
      - build/ios/iphonesimulator/app.zip
