workflows:
  ios_unsigned_build:
    name: iOS Unsigned Build
    environment:
      vars:
        FLUTTER_VERSION: stable
      flutter:
        version: "$FLUTTER_VERSION"
      xcode:
        version: "14.0" # Укажите конкретную версию Xcode
    triggering:
      events:
        - push
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Run Flutter tests
        script: |
          flutter test
      - name: Build iOS unsigned build
        script: |
          flutter build ios --no-codesign
    artifacts:
      - build/ios/Debug-iphoneos/*.app
