name: weather_fl
description: "A weather flutter app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.7
  dio: ^5.7.0
  json_annotation: ^4.9.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700